GET https://63ca4b894f53a00420202b84.mockapi.io/allusers

####



PUT https://63ca4b894f53a00420202b84.mockapi.io/allusers/28
Content-Type: application/json

  {
    "fav" : []
  }


###
DELETE https://63ca4b894f53a00420202b84.mockapi.io/allusers/24

